version: 2
updates:
  - package-ecosystem: "pub" # or "pip", "maven", "docker", etc.
    directory: "/"           # location of package files
    schedule:
      interval: "daily"      # "daily", "weekly", or "monthly"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "chore"
    rebase-strategy: "auto"
