name: Syft + Grype Scan

on:
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  sbom-and-scan:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate SBOM with Syft
        uses: anchore/sbom-action@v0
        with:
          output-file: sbom.spdx.json
          format: spdx-json

      - name: Scan SBOM with Grype (table output in logs)
        uses: anchore/scan-action@v3
        with:
          sbom: sbom.spdx.json
          fail-build: false
          severity-cutoff: medium
          output-format: table

      - name: Scan SBOM with Grype (json output to file)
        run: |
          docker run --rm -v "${{ github.workspace }}:/data" anchore/grype sbom:/data/sbom.spdx.json -o json > grype-output.json

      - name: Upload SBOM as artifact
        uses: actions/upload-artifact@v3
        with:
          name: sbom
          path: sbom.spdx.json

      - name: Upload Grype JSON scan result as artifact
        uses: actions/upload-artifact@v3
        with:
          name: grype-json-output
          path: grype-output.json
