name: Syft + Grype Scan

on:
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  sbom-and-scan:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Generate SBOM with Syft Docker
        run: |
          docker run --rm -v "${{ github.workspace }}:/src" anchore/syft:latest syft /src -o spdx-json > sbom.spdx.json

      - name: Scan SBOM with Grype Docker (table output)
        run: |
          docker run --rm -v "${{ github.workspace }}:/workdir" anchore/grype:latest sbom:/workdir/sbom.spdx.json -o table

      - name: Scan SBOM with Grype Docker (json output)
        run: |
          docker run --rm -v "${{ github.workspace }}:/workdir" anchore/grype:latest sbom:/workdir/sbom.spdx.json -o json > grype-output.json

      - name: Upload SBOM artifact
        uses: actions/upload-artifact@v4
        with:
          name: sbom
          path: sbom.spdx.json

      - name: Upload Grype JSON artifact
        uses: actions/upload-artifact@v4
        with:
          name: grype-json-output
          path: grype-output.json
