name: Trivy FS Scan

on:
  pull_request:
    branches: [master]
  workflow_dispatch:  # Allows manual trigger from GitHub UI

jobs:
  trivy-fs-scan:
    name: Trivy File System Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Trivy
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: '.'
          severity: 'CRITICAL,HIGH'
          exit-code: '1'
          ignore-unfixed: false

