name: zap Scan

on:
  pull_request:
    branches: [master]
  workflow_dispatch:  

jobs:
  sbom-and-scan:
    runs-on: ubuntu-latest
    permissions:
      contents: write  
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate SBOM with Syft
        uses: anchore/sbom-action@v0
        with:
          output-file: sbom.spdx.json
          format: spdx-json

      - name: Scan SBOM with Grype
        uses: anchore/scan-action@v3
        with:
          sbom: sbom.spdx.json
          fail-build: false
          severity-cutoff: medium
